### ISSUE TITLE
Feature Request: Save functions

### ISSUE THREAD

**Issue by schme16** [Zal0/ZGB#11]
I'm loving working with ZGB so far, builds fast, reasonably documented, good start up tutorials, etc.

My current project doesn't _need_ saves but it would be great to be able to add them :)

**Comment by Zal0** [comment]
I got a list of features I'd like to work on first, but sure, savegames is something I'll add eventually

**Comment by schme16** [comment]
Great to hear!
Can't wait to see what features you add in between then and now 😄

**Comment by mhughson** [comment]
+1

**Comment by Zal0** [comment]
There you go
https://github.com/Zal0/ZGB/commit/6b69151debe8edc3c1218f1fde4c555b1c5d19c1#diff-20a77aff38444bd5b9a38e279ff3483b6d79df7ed261dab8b1a587c12a92fe9f
