### ISSUE TITLE
Feature Request: Add pngb to tools in evn folder

### ISSUE THREAD

**Issue by schme16** [Zal0/ZGB#12]
I looked for AGES for a simple image to c converted that _ALSO_ did colour, the only one I've found so far is: pngb - https://github.com/battlecoder/pngb

Figured that if I had that much trouble, having it listed or included might help others out too.

**Comment by Zal0** [comment]
I've been testing it... it seems that it always generates an annoying attribute table that takes precious rom space... any other suggestions?

**Comment by schme16** [comment]
Ahh, fair enough. I'm new enough to all of this I guess i didn't notice
that... I've done quite a bit of looking around and only found this and a
web tool that is no longer hosted, but I'll find the link and post it
anyway, as it might be a case of just spinning up a heroku instance to
serve it up.

**Comment by Zal0** [comment]
Pngs are automatically converted now using a modified version of pngb
https://github.com/Zal0/pngb
I have changed a few default options and modified how data is exported to fit into ZGB
