### ISSUE TITLE
Error with ZGB-Template with the latest version

### ISSUE THREAD

**Issue by aiguanachein** [Zal0/ZGB#13]
Hello! First of all, thanks for this wonderfull engine.

I've got a problem with the latest version, I've updated engine and game code to work with it, but  I cannot compile any of the test i was making before all the changes in the engine were made. I try to redownload all and configure again and with the new template, but the results are the same. If I restore the previous game code and ZGB enviroment, everything is Ok.

There goes an attachement with the result:
  
![imagen](https://user-images.githubusercontent.com/4067447/62546804-7a52d500-b864-11e9-9192-d62a27a9fe7e.png)

Thanks in advance!

`C:\ZGB\proyectos\ZGB-template-master>cd src

C:\ZGB\proyectos\ZGB-template-master\src>c:/ZGB/common\..\env\make-3.81-bin\bin\make run
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
El sistema no puede encontrar la ruta especificada.
Creating folder ../res/src
La sintaxis del comando no es correcta.
Error writing fileCreating folder ../Release/zgb
La sintaxis del comando no es correcta.
common\..\env\make-3.81-bin\bin\make: *** [../Release/zgb] Error 1

C:\ZGB\proyectos\ZGB-template-master\src>cd ..

C:\ZGB\proyectos\ZGB-template-master>pause
Presione una tecla para continuar . . .`

**Comment by cubicstyle** [comment]
The problem is this fix.
https://github.com/Zal0/ZGB/commit/8b2077b7859690ec5fe280520f664b0a60e301c9#diff-67bceb39f464519af34902eaf124b443

Change ":" back to ";" in PATH. Then you can build.

**Comment by Zal0** [comment]
That shouldn't be an issue
using colons instead of semicolons is the standard way to set the path (and it works for me)

**Comment by Zal0** [comment]
> 
> 
> Hello! First of all, thanks for this wonderfull engine.
> 
> I've got a problem with the latest version, I've updated engine and game code to work with it, but I cannot compile any of the test i was making before all the changes in the engine were made. I try to redownload all and configure again and with the new template, but the results are the same. If I restore the previous game code and ZGB enviroment, everything is Ok.
> 
> There goes an attachement with the result:
> 
> ![imagen](https://user-images.githubusercontent.com/4067447/62546804-7a52d500-b864-11e9-9192-d62a27a9fe7e.png)
> 
> Thanks in advance!
> 
> `C:\ZGB\proyectos\ZGB-template-master>cd src
> 
> C:\ZGB\proyectos\ZGB-template-master\src>c:/ZGB/common..\env\make-3.81-bin\bin\make run
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> El sistema no puede encontrar la ruta especificada.
> Creating folder ../res/src
> La sintaxis del comando no es correcta.
> Error writing fileCreating folder ../Release/zgb
> La sintaxis del comando no es correcta.
> common..\env\make-3.81-bin\bin\make: *** [../Release/zgb] Error 1
> 
> C:\ZGB\proyectos\ZGB-template-master\src>cd ..
> 
> C:\ZGB\proyectos\ZGB-template-master>pause
> Presione una tecla para continuar . . .`

It's not clear to me what the problem is beacuse I cannot see the full log
That's the latest version of the template work for you?

I have been making a lot of changes in the recent weeks that I'm sorry but are not backwards compatible. If it is an old project that you were working on you probably need to make a few changes in the code to make it work again. I can help you if you send me a link of your projects

**Comment by aiguanachein** [comment]
The error occurs just compiling the new template, without any changes in the code. I followed the installation guide point by point. I understand that the new template should still work "as is" as shown [here](https://github.com/Zal0/ZGB/wiki/Creating-a-New-Project).
It's strange, cause if I put back the old template and old ZGB folder it works.

**Comment by Zal0** [comment]
Did the solution provided by cubicstyle  work for you?

**Comment by aiguanachein** [comment]
I will try in a couple of hours (I'm not at home now xD) and post the result.
Thanks to all!

**Comment by cubicstyle** [comment]
I'm using Windows 10.
back to colon in PATH, build failed.

**Comment by Zal0** [comment]
Windows 10 also here and no problems at all...
are you using msys2?

**Comment by cubicstyle** [comment]
msys2 is installed.
not used for build it.

**Comment by aiguanachein** [comment]
Working with the solution provided by @cubicstyle, at least on Windows 7. I will try later on Win 10.

**Comment by aiguanachein** [comment]
Works on Win 10 (1903) too.

**Comment by cubicstyle** [comment]
I tried on another Windows 10 PC, it was  same build error.

my windows lang environment  is Japanese.
may be set lang other than English.
![zgb_error](https://user-images.githubusercontent.com/20790149/62636267-2f27e780-b974-11e9-902c-6b99b6de89b4.jpg)

**Comment by Zal0** [comment]
Using semicolons fails on that japanesse computer?
I was about to revert that commit

**Comment by cubicstyle** [comment]
yes, I can build by modify to semicolons.

@aiguanachein  is also not English environment.

**Comment by Zal0** [comment]
Tested with msys2 on my computer and no issues at all
Did you guys modified the content of the env folder? are you still using make 3.81 for Windows?

**Comment by aiguanachein** [comment]
@Zal0 No, is just unzipped from the link provided. And in my case as far as I know i'm not using msys2.

**Comment by Zal0** [comment]
Ok, I have reverted the changes. I'll review this for Linux when the times come, in the meantime I want this working on Windows without problems
Thank you guys for your help!
