### ISSUE TITLE
Problems with 32x32 Sprites

### ISSUE THREAD

**Issue by aiguanachein** [Zal0/ZGB#14]
I'm having problems with 32x32 sprites. 
This is how it should appear (in the previous versions of ZGB it was working ok):
![image ok](https://user-images.githubusercontent.com/4067447/62712260-c33c9200-b9fa-11e9-9457-90aeb1b84708.png)
And this is how appears now:
![image wrong](https://user-images.githubusercontent.com/4067447/62712268-c9327300-b9fa-11e9-8348-d3418b2de4f6.png)

As I see, the problem is with the automatically exported file. Here I left an attached a file with the file exported from GBTD (enemy3 (ok).b3.c) and the automatically generated file (enemy3 (wrong).b3.gbr.c). As you can see, the sprite array is not the same.

Thanks in advance!

[enemy3.zip](https://github.com/Zal0/ZGB/files/3482255/enemy3.zip)

**Comment by Zal0** [comment]
Fixed in the last commit
