### ISSUE TITLE
Check specific tile at specific location ?

### ISSUE THREAD

**Issue by rodentcat** [Zal0/ZGB#26]
Hi !

I was wondering about something. I'm trying to make a game where you get to stick to walls and ceilings and stuff, but I can't figure out how to check the collision tiles at a certain point. I'm mainly wondering what the .... command ? is that the word ?
I'm wondering what the command is for that. I thought "GetScrollTile" might do the trick, but.... Yeah, that's not working.

![image](https://user-images.githubusercontent.com/31519042/113179299-b2164980-920c-11eb-803f-2d6869ca09fe.png)

If it doesn't exist already, I was wondering if you could add it ?  I've been looking through the include files for anything that could help, but... I couldn't find anything. Maybe I'm blinding on it...

**Comment by aiguanachein** [comment]
As far as I kwow GetScrollTile should do the trick, but you need to add the shifting to each coordinate
`GetScrollTile(THIS->x >>3, (THIS->y + 2 )>>3) == 1)`
Anyway, if the tiles you want to check are collideable TranslateSprite function returns the tile number if the sprite and tile collide.

**Comment by PnkMyo** [comment]
Thank you so much ! It worked ! :D 
The reason I'm not doing TranslateSprite is because you're able to jump again when you hit a ceiling. I'm probably doing something wrong, but for the game I'm doing, I want you to be able to stick to the ceiling, and by extension, walls.

**Comment by Zal0** [comment]
I am closing this since it doesn't look like a bug
