### ISSUE TITLE
Add LCD_isr(); function declaration to main header

### ISSUE THREAD

**Issue by aiguanachein** [Zal0/ZGB#34]
Just a stupid suggestion, could you add void LCD_isr(); declaration to main.h? in case you want to remove this interruption to have the sprites over the window. It's an easy tweak, but if it's already included in ZGB it's always better.
Thanks in advance!

**Comment by Zal0** [comment]
Done 
https://github.com/Zal0/ZGB/commit/ac57350efccb56cf4b32b62c45be5e89405f8f23
