### ISSUE TITLE
SpriteManagerLoad() issue loading multiple color palettes from disparate sprites

### ISSUE THREAD

**Issue by martzgb** [Zal0/ZGB#35]
I'm observing an issue where the last sprite loaded has its color palette overwrite previous sprites palettes.

<img width="609" alt="Screen Shot 2021-11-22 at 8 08 56 PM" src="https://user-images.githubusercontent.com/94885923/142972706-c82c6fe9-5416-4b44-8e4e-e3b686a3340a.png">

- a grey box that is supposed to be green. generated from a gbr.
- a person that appears correct on the right and wrong on the left. generated from a png.
- a blue hint window that is correct generated from a png.

<img width="782" alt="Screen Shot 2021-11-22 at 8 41 59 PM" src="https://user-images.githubusercontent.com/94885923/142972834-b2687892-be45-4d71-aa02-072ae1c518e0.png">

I think the strncmp is trying to allow multiple sprites that are sharing colors to share a hardware palette? I don't think it's functioning correctly. Perhaps after filing this issue I'll try to find a more proper fix.

**Comment by Zal0** [comment]
I was using strncmp instead of memcmp... since there is no memcmp yet on GBDK I have added a custom implementation temporarily, but this fixes the bug for now

https://github.com/Zal0/ZGB/commit/6bedcf160723a95595d21f70ae8d229d34373584
