### ISSUE TITLE
Enhancement Request: Option not to stop music when changing game states

### ISSUE THREAD

**Issue by martzgb** [Zal0/ZGB#36]
There is a call to `StopMusic;` on line 136 of main.c. The levels in my game can be quite short, and it would be nice to be able to conditionally continue playing music. At least in my project, if I comment out this line, music continues playing fine.

**Comment by Zal0** [comment]
Done on
https://github.com/Zal0/ZGB/commit/a503ed3a52b5418a8402f2d96efae9c1f85be896
