### ISSUE TITLE
Errors in Enemy Sprite section of tutorial

### ISSUE THREAD

**Issue by mhughson** [Zal0/ZGB#39]
> Save the file into the res/ folder as enemy.gbr (the b3 before the gbr extension indicates that we want to save this sprite on bank 3, notice how all the resources in the template are also stored in bank3 by default)
https://github.com/Zal0/ZGB/wiki/Enemies

This section has 2 errors:

1. The parts about banks (b3) are no longer relevant.
2. The file must be saved into res/Sprites/ (not just res). Otherwise, the game will crash.

**Comment by Zal0** [comment]
fixed
