### ISSUE TITLE
Error in Maps section of Tutorial

### ISSUE THREAD

**Issue by mhughson** [Zal0/ZGB#40]
> Open the tiles.bgr with the Game Boy Tile Designer and go to View->Tile Count and set that to 255. Now edit the tile 254 that corresponds to the sprite of type 1 (SPRITE_ENEMY) and create a thumbnail of the enemy

https://github.com/Zal0/ZGB/wiki/Maps

This part of the tutorial assumes that tiles.gbr is setup for 256 tiles, but it only has 128.

**Comment by Zal0** [comment]
But it's actually telling you to change that to 255 before editing tile 254, it seems ok
