### ISSUE TITLE
Missing information in Music section of tutorial

### ISSUE THREAD

**Issue by mhughson** [Zal0/ZGB#41]
In the music section of the tutorial (https://github.com/Zal0/ZGB/wiki/Music) the part about declaring the music is slightly confusing.

First, the template using HUDTRACKER by default, not GBT_PLAYER. The tutorial doesn't seem to work with HUGETRACKER (linker errors), so it requires that the user editor the Makefile here:

`# Music player: HUGETRACKER(default) or GBT_PLAYER
MUSIC_PLAYER = GBT_PLAYER`

> Modify it and save it with a different name. Don't forget to include in what bank the music should be (level1.mod for example).

This talks about setting the bank that the music should live in, but I'm pretty sure that isn't required anymore, as the project using automatic banking.

Additionally, there is a missing step to "include music.h".

**Comment by Zal0** [comment]
Fixed
I have also pushed this so the project will be fully recompiled after making any change on the Makefile
https://github.com/Zal0/ZGB/commit/324479fcf9253efb5aa941f1b3cf9746034a976b
