### ISSUE TITLE
Incorrect initialization of hUGEDriver

### ISSUE THREAD

**Issue by SuperDisk** [Zal0/ZGB#48]
[This line](https://github.com/Zal0/ZGB/blob/dfe2552a54ab0fab57b6de8e0dd433b87885f30e/common/include/Music.h#L16) is incorrect; `hUGE_init` is for initializing to a song descriptor, but `0` isn't one. Up until now, I believe this went unnoticed since `hUGE_init` doesn't do any unbounded looping, but when I added song decompression to a fork of hUGEDriver, this broke.

Here's a patch which fixes things up :)
```diff
diff --git a/common/include/Music.h b/common/include/Music.h
index 8ed475d..e36ae0c 100644
--- a/common/include/Music.h
+++ b/common/include/Music.h
@@ -13,7 +13,7 @@ void MusicCallback() __nonbanked;
 	extern BYTE hUGE_paused;
 	void hUGE_mute(UBYTE mute);
 
-	#define INIT_MUSIC hUGE_init(0)
+	#define INIT_MUSIC
 	#define DECLARE_MUSIC(SONG) extern const void __bank_ ## SONG ## _uge; extern const hUGESong_t SONG ## _uge
 	#define PlayMusic(SONG, LOOP) __PlayMusic(&SONG ## _uge, (uint8_t)&__bank_ ## SONG ## _uge, 0)
 	#define StopMusic hUGE_paused = 1; hUGE_mute(HT_CH_MUTE); last_music = 0
```

**Comment by Zal0** [comment]
Thaks for the info, I have updated the code in this commit https://github.com/Zal0/ZGB/commit/b64f79c715cdba1a57947bddd0b73bfa78dc46ce
