### ISSUE TITLE
Default SaveGame Values

### ISSUE THREAD

**Issue by mhughson** [Zal0/ZGB#51]
Often a save file should not be completely zero'd out by default.

It would be nice if the SRAM API allowed for either passing in a "default" savegame struct to copy in the case of CheckSRAMIntegrity needing to clear out the save. Alternatively, some sort of callback that the game could implement would work too.

**Comment by mhughson** [comment]
I got around this by adding my own very basic "integrity check" in my games initial state.

```
// savegame.h
typedef struct {
  SAVEGAME_HEADER;

  //Whatever content you want to store in external ram
  unsigned char version;

  // Is the music and sound currently enabled?
  unsigned char music_on;
  unsigned char sfx_on;
...
```

```
// in START() of my initial state...

	if (savegame.version == 0)
	{
		savegame.version = 1;
		savegame.music_on = 1;
		savegame.sfx_on = 1;
	}
```

**Comment by Zal0** [comment]
Yes, I was going to suggest that
