### ISSUE TITLE
Problem with Enemies section.

### ISSUE THREAD

**Issue by jermsworms** [Zal0/ZGB#54]
I followed the tutorial for creating enemies. when I define the enemy sprite I get this error. 

?ASlink-Warning-Undefined Global '_Start_SpriteEnemy' referenced by module 'ZGBMain_Init'

?ASlink-Warning-Undefined Global '___bank_SpriteEnemy' referenced by module 'ZGBMain_Init'

?ASlink-Warning-Undefined Global '_Update_SpriteEnemy' referenced by module 'ZGBMain_Init'

make: *** [../bin/ZGB_TEMPLATE.gb] Error 2

**Comment by Zal0** [comment]
You are doing something wrong. Check Enemy.c, START and UPDATE methods
