### ISSUE TITLE
Failure to use music 

### ISSUE THREAD

**Issue by p1nhead98** [Zal0/ZGB#55]
I declare the music and use it as indicated in the documentation but I get this error when I save a song .uge in the res/music folder 

![sus](https://user-images.githubusercontent.com/57465825/199634877-58965783-bbbc-4ec6-97d1-c4c4a08b96dd.png)

**Comment by aiguanachein** [comment]
Same here!

**Comment by nygator** [comment]
Are you using hUGEtracker 1.0b10? Because that's not compatible with ZGB right now. The new version changed how the music format works. I fixed this by manually compiling all the music into c files and putting them into the /Debug/res/ folder and manually replacing the driver with a new one, then realised how much work this is and just switched back to hUGEtracker 1.0b9.

I hope Zal0 adds an option to switch between different sound drivers and hUGEtracker versions... :\

**Comment by aiguanachein** [comment]
I tried with one of the sample songs that come in the package hUGETracker 1.0 Beta 9.zip (renamed to test.uge), but it doesn't seem to work either. 
![error](https://user-images.githubusercontent.com/4067447/202226630-bf5fa82b-e19a-4d0e-9a63-2e4d9394303f.png)

**Comment by ItsMeSousuke** [comment]
When I removed from https://github.com/Zal0/ZGB/blob/master/common/include/hUGEDriver.h all the OLDCALL, it starts working. What was the reason of adding that OLDCALL to the code?

**Comment by Zal0** [comment]
> When I removed from https://github.com/Zal0/ZGB/blob/master/common/include/hUGEDriver.h all the OLDCALL, it starts working. What was the reason of adding that OLDCALL to the code?

You need that to use the latest GBDK

**Comment by ItsMeSousuke** [comment]
So how it's possible that it works without it, because all the other things all compiled before and are not recompiled?

**Comment by greenwebsevilla** [comment]
> So how it's possible that it works without it, because all the other things all compiled before and are not recompiled?

This works for me: removing the OLDCALLs to compile the song, then I have to restore the OLDCALLs to make it sound fine. It is not the best solution, but it works for now. I will test it during the development. I case I find any issue or a better solution I will write here.

**Comment by wirehack7** [comment]
> > So how it's possible that it works without it, because all the other things all compiled before and are not recompiled?
> 
> This works for me: removing the OLDCALLs to compile the song, then I have to restore the OLDCALLs to make it sound fine. It is not the best solution, but it works for now. I will test it during the development. I case I find any issue or a better solution I will write here.

How exactly is your process there?
Removing oldcalls and then _only_ compile the song?
And then restoring oldcall and compiling the project?

**Comment by Zal0** [comment]
Adding #include <gb/gb.h> into hUGEDriver.h fixes the issue   
The problem is that OLD_CALL needs that include to compile 

I have fixed this now
