### ISSUE TITLE
Problems displaying HUD Window in games compiled in Color mode when running on B/W hardware

### ISSUE THREAD

**Issue by aiguanachein** [Zal0/ZGB#56]
When compiling a game in Color mode and executing on B/W hardware the HUD Window doesn't appear correctly, e.g. not displaying any text printed by Printf.
When compiling in classic mode or when compiling in Color and running in GBC  appears Ok.

**Comment by aiguanachein** [comment]
Fixed adding cpu=CGB_TYPE conditional
![Captura de pantalla 2023-05-25 184802](https://github.com/Zal0/ZGB/assets/4067447/b8da5703-978d-4075-840d-c8546a958700)

**Comment by Zal0** [comment]
Thanks!
