### ISSUE TITLE
[Request] [Docs] Debian/Ubuntu instructions for compiling in wiki

### ISSUE THREAD

**Issue by BeauBouchard** [Zal0/ZGB#59]
### Description of Changes

I recently have started using this library and first, thank you for all your hard work you put into it. Its very impressive and heavily enriches the community of game boy developers. 

I use Ubuntu on desktop and I would like to help refine some instructions for the wiki to help other developers using this repo on linux. I was wondering if we could have a "installation / building" page separate from the [Creating a New Project Wiki Page](https://github.com/Zal0/ZGB/wiki/Creating-a-New-Project). Ideally this page can lead with the expected installation with windows, but could have a header for linux building instructions with some more specific commands. I read your post in https://github.com/Zal0/ZGB/issues/10#issuecomment-469545384 and believe that the instructions you gave are spot on, and with a little refinement would be a very good start for the wiki page. 

Thank you again for your time, and I would love to help with this if I can.

**Comment by BeauBouchard** [comment]
One more Suggestion 

I want to also take this time to make a case for a `Installation.md` file, by having the documentation in the codebase it allows more people to commit PRs against it, as currently I can't make a suggestion to edit to the wiki pages, its only for the main contributor to steward.

**Comment by Zal0** [comment]
Linux is not yet supported

**Comment by BeauBouchard** [comment]
:+1: thank you for your time, and let me know if you need assistance in the future on this should you decide to pursue linux as a target.

**Comment by ash2q** [comment]
Could someone else contribute these alternate platform instructions? I'm also trying to use this on a unix platform and there's missing files for compiling the tools (specifically gbrParser.h is missing)
