### ISSUE TITLE
Compiling issue (__sdcc_call_hl.s)

### ISSUE THREAD

**Issue by ghost** [Zal0/ZGB#6]
I'm having an issue compiling any games with this tool, it works fine on my laptop but on my desktop I get an error when it starts on __sdcc_call_hl.s. The error that pops up calls out sdasgb.exe

The text from cmd reads

`make: Entering directory `c:/ZGB/common/src'
compiling __sdcc_call_hl.s
make: *** [../Release/__sdcc_call_hl.o] Error -1073741502
make: Leaving directory `c:/ZGB/common/src'

C:\Users\digis\Downloads\ZGB-template-master\ZGB-template-master>cd src

C:\Users\digis\Downloads\ZGB-template-master\ZGB-template-master\src>C:\gbdk\bin\make-3.81-bin\bin\make run
compiling resource: ../res/src/font.b3.c
      0 [main] sh 16880 sync_with_child: child 13780(0x208) died before initialization with status code 0xC0000142
    105 [main] sh 16880 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
make: *** [../Release/res/font.b3.o] Error 128

C:\Users\digis\Downloads\ZGB-template-master\ZGB-template-master\src>cd ..

C:\Users\digis\Downloads\ZGB-template-master\ZGB-template-master>pause
Press any key to continue . . .`

If this isn't where this should be posted, let me know where I should move it. 

Thanks

**Comment by Zal0** [comment]
This is probably caused by having an output too large... I have moved all compiled obj from zgb engine to the project itself. This saves a lot of character, I think it should be enough for now
