### ISSUE TITLE
Errors with ZGB-template

### ISSUE THREAD

**Issue by bkmak** [Zal0/ZGB#61]
I downloaded the latest ZGB-template-master and opened the solution in Visual Studio 2022 Community Edition. Immediately, I am seeing errors in the Error List such as:

E0070 incomplete type is not allowed

![image](https://github.com/Zal0/ZGB/assets/33822064/2df8f1fd-6f57-407c-99d0-18606c12b120)

E0260 explicit type is missing ('int' assumed)

![image](https://github.com/Zal0/ZGB/assets/33822064/7aea81f8-7331-4ab3-8992-ec73e7a1c19d)

E0065 expected a ';'

![image](https://github.com/Zal0/ZGB/assets/33822064/37136032-7b95-4f0e-a83a-1cff2f3288be)

I did install the latest release of ZGB and ran install.bat.

**Comment by Zal0** [comment]
That's a known issues... but I am afraid is VS meshing things up... if you try to compile it should do it without problems
