### ISSUE TITLE
No flag on sprite to declare transparent color

### ISSUE THREAD

**Issue by dalejwilliams** [Zal0/ZGB#9]
I'm not sure if this is a limitation of ZGB or GBDK, but it seems as though there isn't a way to set which of the four sprite colors is transparent.

**Comment by dalejwilliams** [comment]
By the way, I really like your engine. I'm only a beginner to GB dev, and C, but it's well written and easy to understand so far.

**Comment by Zal0** [comment]
I'm glad you like it

The first color in the palette is the transparent one, it is a hardware limitation as far as I know
